### ISSUE TITLE
Xvnc unusable without flow control enabled

### ISSUE THREAD

**Issue by rbhkamal** [TurboVNC/turbovnc#40] opened 2016-06-10 22:17 UTC
TurboVNC Server (Xvnc) 64-bit v2.0.91 (build 20160610d)

**Description:**
When connecting to TurboVNC Server without flow control/continuous updates, Xvnc starts to send 1x1 pixel rectangle updates. For clients that don't throttle the RFBUR, this causes them to use %100 CPU and ton of bandwidth. Essentially making both the server, network and client super slow. This is also an issue for any older client (i.e. TurboVNC 1.1).

**Steps:**
1- ./Xvnc :1 -interframe -securitytypes none -geometry 1920x1200
2- /opt/TurboVNC/bin/vncviewer -nocu localhost:1
2- or use turbo vncviewer V1.1 (vncviewer localhost:1)
3- mwm -display :1 (or start anything that changes the shape of the pointer)

To work around this problem, you must disable "X-style cursor updates" and "full-color cursor updates", then the problem goes away. But of course, that is not a solution. It is as if the Xvnc server continuously thinks that the cursor position or shape are getting updated. I think something inside rfbSendFramebufferUpdate is messing with the cursor causing an semi-infinite loop. 

**Details from debugging:**
So here is the sequence of events as I understand it through debugging the Xvnc server:
1- After initialization, client sends RFBUpdateRequest to the server
2- Server starts processing request
3- Server decides for some reason to call rfbSendFramebufferUpdate. Perhaps something is wrong with FB_UPDATE_PENDING
4- rfbSendFramebufferUpdate then seems to try to update some buffer to remove the mouse pointer (because X-Style updates are enabled)
5- Black magic inside rfbSpriteRemoveCursorAllDev ends up modifying cl->modifyedRegion
6- rfbSendFramebufferUpdate tries to send the update but detects that there is no actual change in the buffer
7- Code introduced in 17e874130603a2fde696a355e01b39df1333ac56 then decides to send a single pixel update.
8 - Client gets the update then back to step 1

If I comment out the call to rfbSpriteRemoveCursorAllDev in rfbSendFramebufferUpdate(), the the issue doesn't happen.

I also verified via wireshark that the 1x1 rectangle is all that is actually changing.
![vnc no change in frame buffer](https://cloud.githubusercontent.com/assets/4822459/15980156/1dad0fbe-2f37-11e6-9274-fe845fabe433.png)

It seems like this would an easy fix for someone that knows what "sprite" is. Any help would be greatly appreciated.

**Comment by dcommander** [comment] 2016-06-10 22:42
I'll look into it, but it may be a few weeks.  There are some other issues in the server-side cursor rendering mechanism that are causing rendering problems whenever cursor shape updates are disabled, and I suspect that this is related.  I need to get rid of the old sprite-based mechanism, as it doesn't seem to work well with the newer X.org code base.

**Comment by dcommander** [comment] 2016-06-10 22:42
Possibly the same root cause as #38

**Comment by rbhkamal** [comment] 2016-06-10 23:58
Thanks dcommander!

**Comment by dcommander** [comment] 2016-07-19 01:52
Sorry this is taking so long.  I've been traveling a lot and working actively on a contract for Intel.  I don't like to get this far behind on TurboVNC bug fixes, but unfortunately I'm still having trouble nailing this one down, because it's so closely tied to the server-side cursor rendering bug (it seems that if I fix one bug, the other re-surfaces, and vice versa.)  Since we're already in beta, I'm trying to find a solution that doesn't involve rewriting all of the cursor handling code.

As you point out, removing the call to rfbSpriteRemoveCursorAllDev() prevents the high CPU usage, but this also causes incorrect cursor behavior (the cursor is shown both on the remote and local desktops.)  I'll keep you posted.  TurboVNC 2.1 is ridiculously overdue, but this fix absolutely needs to go into it.  I'll keep you posted.

**Comment by rbhkamal** [comment] 2016-07-19 12:54
no problem, I've implemented rudimentary throttling on the client to keep the traffic down so this issue is not bothering us so much. 

I was thinking about a potential hack. I think we might be able to work around this if the code introduced in https://github.com/TurboVNC/turbovnc/commit/17e874130603a2fde696a355e01b39df1333ac56 is updated so that instead of sending a message to the client and then waiting for the client to send an RFBU request, the Xvnc server just triggers a throttled signal that is handled as a RFBU Request without sending any messages to the client. This keeps that hack effectively the same but at least it eliminates the network and the client(s) from this infinite loop.

**Comment by dcommander** [comment] 2016-07-20 04:49
Fixing this issue is actually straightforward. It's just a matter of figuring out how to fix both it and the server-side cursor rendering bug at the same time. I got really close yesterday but had to put it aside again because of more pressing matters. I'll be able to focus on it next week.

**Comment by dcommander** [comment] 2016-08-02 00:47
I checked in a fix for this in my local sandbox, but I'm holding off on pushing it until #38 is resolved, since resolving that may require modifying my fix for this.  Here is a temporary patch if you want to test it in the meantime.

```
diff --git a/unix/Xvnc/programs/Xserver/hw/vnc/draw.c b/unix/Xvnc/programs/Xserv
er/hw/vnc/draw.c
index c3312a4..30769a6 100644
--- a/unix/Xvnc/programs/Xserver/hw/vnc/draw.c
+++ b/unix/Xvnc/programs/Xserver/hw/vnc/draw.c
@@ -11,7 +11,7 @@
 
 /*
  *  Copyright (C) 1999 AT&T Laboratories Cambridge.  All Rights Reserved.
- *  Copyright (C) 2010-2012, 2014 D. R. Commander.  All Rights Reserved.
+ *  Copyright (C) 2010-2012, 2014, 2016 D. R. Commander.  All Rights Reserved.
  *  Copyright (C) 2012-2013, 2016 Pierre Ossman for Cendio AB.
  *                                All Rights Reserved.
  *
@@ -122,8 +122,11 @@ static inline Bool is_visible(DrawablePtr drawable)
       BoxRec *box = REGION_EXTENTS(pScreen, reg);                             \
       if ((box->x2 - box->x1) * (box->y2 - box->y1) != 0)                     \
           for (cl = rfbClientHead; cl; cl = cl->next) {                       \
-              REGION_UNION((pScreen), &cl->modifiedRegion,                    \
-                           &cl->modifiedRegion, reg);                         \
+              if (!prfb->dontSendFramebufferUpdate ||                         \
+                  !cl->enableCursorShapeUpdates) {                            \
+                  REGION_UNION((pScreen), &cl->modifiedRegion,                \
+                               &cl->modifiedRegion, reg);                     \
+              }                                                               \
           }                                                                   \
   }
 
@@ -136,8 +139,11 @@ static inline Bool is_visible(DrawablePtr drawable)
       BoxRec *box = REGION_EXTENTS(pScreen, reg);                             \
       if ((box->x2 - box->x1) * (box->y2 - box->y1) != 0)                     \
           for (cl = rfbClientHead; cl; cl = cl->next) {                       \
-              REGION_UNION((pScreen), &cl->alrEligibleRegion,                 \
-                           &cl->alrEligibleRegion, reg);                      \
+              if (!prfb->dontSendFramebufferUpdate ||                         \
+                  !cl->enableCursorShapeUpdates) {                            \
+                  REGION_UNION((pScreen), &cl->alrEligibleRegion,             \
+                               &cl->alrEligibleRegion, reg);                  \
+              }                                                               \
           }                                                                   \
   }
 
@@ -344,7 +350,9 @@ rfbCopyWindow(WindowPtr pWin, DDXPointRec ptOldOrg, RegionPtr pOldRegion)
             REGION_INIT(pScreen, &srcRegion, NullBox, 0);
             REGION_COPY(pScreen, &srcRegion, pOldRegion);
 
-            rfbCopyRegion(pScreen, cl, &srcRegion, &dstRegion, dx, dy);
+            if (!prfb->dontSendFramebufferUpdate ||
+                !cl->enableCursorShapeUpdates)
+                rfbCopyRegion(pScreen, cl, &srcRegion, &dstRegion, dx, dy);
 
             REGION_UNINIT(pSrc->pScreen, &srcRegion);
 
@@ -695,9 +703,11 @@ rfbCopyArea(DrawablePtr pSrc, DrawablePtr pDst, GCPtr pGC, int srcx, int srcy,
                                      &((WindowPtr)pSrc)->clipList);
                 }
 
-                rfbCopyRegion(pSrc->pScreen, cl, &srcRegion, &dstRegion,
-                              dstx + pDst->x - srcx - pSrc->x,
-                              dsty + pDst->y - srcy - pSrc->y);
+                if (!prfb->dontSendFramebufferUpdate ||
+                    !cl->enableCursorShapeUpdates)
+                    rfbCopyRegion(pSrc->pScreen, cl, &srcRegion, &dstRegion,
+                                  dstx + pDst->x - srcx - pSrc->x,
+                                  dsty + pDst->y - srcy - pSrc->y);
 
                 REGION_UNINIT(pSrc->pScreen, &srcRegion);
```

This is reproducible without interframe comparison enabled, so it doesn't seem to have anything to do with 17e8741.  Rather, the root cause seems to be that both rfbSpriteRestoreCursor() and rfbSpriteRemoveCursor() are triggering changes to cl->modifiedRegion, because those functions trigger a PushPixels and a CopyArea drawing operation (respectively.)  When remote cursor shape updates are enabled, rfbSendFramebufferUpdate() removes the sprite cursor from the framebuffer prior to sending the update, in order to prevent cursor duplication (since the cursor is being drawn on the client.)  This triggers the viewer to send back a FBUR, but in the meantime, the sprite block handler (called when the server is idle) notices that the cursor is no longer drawn on the framebuffer and attempts to re-draw it.  This triggers rfbSpriteRestoreCursor(), which in turn triggers a PushPixels operation that changes cl->modifiedRegion, so the new FBUR triggers rfbSendFramebufferUpdate(), and because the sprite cursor has been drawn again, rfbSpriteRemoveCursorAllDev() is called again, and the cycle repeats.

The solution (at least for now) is to avoid changing cl->modifiedRegion if prfb->dontSendFramebufferUpdate is TRUE.

**Closed** 2016-08-03 11:37 UTC
Labels: bug
