### ISSUE TITLE
TurboVNC refuses to alter vnc server ip location.

### ISSUE THREAD

**Issue by Mysteriousdewd** [TurboVNC/turbovnc#57] opened 2016-08-31 01:59 UTC
I have attempted 30 times to change my ip address and port number on TurboVNC but it refuses to change to port 5901. It defaults every time to port 1. It will only accept changes to the ip if I do not enter a new port. I am now unable to connect to my vnc server which I was previously able to connect to.

**Comment by dcommander** [comment] 2016-08-31 02:04
Please provide a more detailed description of the problem, including exact steps to reproduce it.  It is unclear from your description exactly what it happening.

TurboVNC of course never uses "port 1."  Do you mean "display :1", which is the same as port 5901?  And what do you mean by "it will only accept changes to the IP if I do not enter a new port"?  Are you referring to a viewer or a server issue?  If it's a viewer issue, which viewer?

Would love to help you out, but you have to help me out first by providing the necessary information to reproduce the problem.

**Comment by Mysteriousdewd** [comment] 2016-08-31 03:59
I'll take some screenshots with the exact steps I am doing and post them here within the next day.

**Comment by dcommander** [comment] 2016-09-07 00:46
Please provide more information as requested, or I will be forced to close this report.  I don't need a screen shot.  I just need you to explain descriptively what the problem is.  "TurboVNC refuses to alter vnc server ip location" is a meaningless phrase.

**Comment by dcommander** [comment] 2016-09-07 22:46
Closing due to lack of response from the submitter.

**Closed by dcommander** 2016-09-07 22:46 UTC
