### ISSUE TITLE
Error: The processing instruction target matching “[xX][mM][lL]” is not allowed

### ISSUE THREAD

**Issue by Ri0n** [TurboVNC/turbovnc#48] opened 2016-08-11 14:09 UTC
When I try to start via web I get message from topic in details. and it fails to connect.
It's with Oracle Java 9 Web Start.

vncviewer does not work either but that's another story.

**Comment by Ri0n** [comment] 2016-08-11 14:18
Retried with IcedTea and it's launched. but does not work anyway. Have to make another report.

Ubuntu 16.04 on client side and Ubuntu 14.04 on server side.
On both sides I have installed turbovnc_2.0.91_i386.deb

vnc server is configured to be started under user which is currently logged in.

**Comment by Ri0n** [comment] 2016-08-11 15:14
Oh I've just figured out the idea itself. vncserver creates a new display, instead of connecting to already running.

so the error is still valid but I'm no more interested in this product.

**Comment by dcommander** [comment] 2016-08-11 15:46
If you need to view an existing display, I recommend x11vnc.  It contains the same codec as the TurboVNC Server.  You can still use our viewer.

Thanks for reporting the issues.  I'll try to reproduce them.

**Comment by dcommander** [comment] 2016-09-07 02:19
This appears to be a problem with JavaWS under Oracle Java 9, and a quick Google search suggests that we're not the only ones encountering it.  It's unclear whether this is due to a new feature in Java 9 that we're not supporting or simply a bug in Java 9, and I don't have time to dig into it right now.  I don't generally support pre-releases of operating systems and other compute infrastructure for this reason.  It doesn't make sense to try to develop against a moving target.  If someone more in-tune with Oracle Java development can suggest why this is happening and submit a patch, I'll be happy to check it in, but in the meantime, I'm closing this as SEP.

**Closed by dcommander** 2016-09-07 02:19 UTC

**Comment by Ri0n** [comment] 2016-09-07 08:05
As I understood from the bug details, TurboVNC generates invalid xml.
Well, but I don't care anymore.

**Comment by dcommander** [comment] 2016-09-07 14:08
The error has to do with parsing the JNLP file.  But since you don't care anymore, I guess I don't either.  Good day.
