### ISSUE TITLE
drawing with inkscape caligraphy tool gives "splotchy" lines

### ISSUE THREAD

**Issue by jave** [TurboVNC/turbovnc#198] opened 2019-10-31 12:48 UTC
To reproduce:

- Start inkscape on the remote end
- enable wacom pressure sensitivity in inkscape
- use the caligraphy tool

if it works correctly, you can now control the stroke width with the pen pressure.

- draw a bit with the tool. Randomly, what appears as inky blobs on the path appears.

- this never happens if you draw using inkscape locally

![image](https://user-images.githubusercontent.com/110042/67947995-12065c00-fbe5-11e9-91d0-cc49055e3b6a.png)

**Comment by jave** [comment] 2021-09-13 20:50
This doesnt happen as frequently now that it used to, so I close this.

**Comment by dcommander** [comment] 2021-09-13 20:55
@jave As far as I know, nothing has changed in TurboVNC 2.2.x that would have fixed this, and "not as frequently" is not the same thing as "fixed."  Please do not close an issue if it is still reproducible.

**Comment by dcommander** [comment] 2021-09-13 20:56
Also, please provide more details regarding your environment.  Which client O/S?  Which drawing tablet?

**Comment by jave** [comment] 2021-09-13 21:13
I cant  really reproduce this  anymore. Previously in 2019, it happened all the time

I now use the turbovnc 3.0 beta. Both client and server are running fedora 34.

The tablet is a hp  laptop, xinput reports the pen as "Wacom HID 481C Pen stylus", but I dont think it is an actual wacom unit, at least not wacom emr. The stylus has a battery in it.

**Comment by dcommander** [comment] 2021-09-13 21:17
There is no 3.0 beta yet.  Please specify which build of TurboVNC 3.0 pre-beta you are using (the build number should be visible in the TurboVNC Viewer's "About" dialog.)  If the build number is later than 202101XX, then the issue may have gone away as a result of upgrading the TurboVNC Helper to use X Input v2.

**Comment by jave** [comment] 2021-09-14 18:58
2.2.80 20210901

**Comment by dcommander** [comment] 2021-09-14 20:40
OK, then this issue was probably fixed in the context of upgrading the TurboVNC Helper to use X Input v2 and adding multitouch support.  I feel like I could probably fix it in TurboVNC 2.2.x as well if I could reproduce the issue.  I'll try to do that before the 2.2.7 release.

**Comment by dcommander** [comment] 2021-12-21 21:54
I ran out of time and funding, unfortunately.  Since this is resolved in 3.0, I am closing as won't fix for 2.2.x.

**Closed by dcommander** 2021-12-21 21:54 UTC
