### ISSUE TITLE
Refresh problems

### ISSUE THREAD

**Issue by mlampe** [TurboVNC/turbovnc#150] opened 2018-11-30 19:44 UTC
See attached picture for demonstration. This is the standard gnome desktop from EL6 (vncserver) displayed on EL7 (vncviewer). I moved around a gnome-terminal window for some time and got what you see. (Turbovnc 2.2, but also 2.1).

![gnom-desktop](https://user-images.githubusercontent.com/1618953/49310191-e7e08180-f4dd-11e8-9a93-9dc0511f4479.png)

Some additional information: This happens with both fvwm and gnome on the displaying machine. If I grab the window inside the remote desktop, the grabbed window is ok. (The window being grabbed is still displayed with all the artifacts.)

**Comment by dcommander** [comment] 2018-11-30 20:58
Weird.  I saw a similar problem with the ancient Xt TurboVNC Viewer that was retired in TurboVNC 2.0:
https://sourceforge.net/p/turbovnc/bugs/6/

but this has never been reported with the newer Java TurboVNC Viewer, nor can I reproduce it currently.  Does it go away if you do either of the following:

1. Disable CopyRect encoding by passing `-nocopyrect` (undocumented command-line parameter) to `/opt/TurboVNC/bin/vncviewer`
2. Enable Swing double-buffering by invoking `export JAVA_TOOL_OPTIONS=-Dturbovnc.swingdb=1` prior to launching `/opt/TurboVNC/bin/vncviewer`

?

If this is in fact the same issue that I observed with the old Xt viewer, then it should only occur when the remote window is dragged partly off of the remote desktop and back onto it again, and only when CopyRect is enabled.  It is almost certainly a client-side issue, but I'm not sure why your client experiences it and my clients don't (differences in the graphics driver, perhaps?)

**Comment by mlampe** [comment] 2018-11-30 21:45
1 and 2 don't help. I also found that you only need to "shake" the window horizontally to get the artifacts.

After some more tests, I think this is a bug recently introduced by RH in both their java-1.7.0-openjdk and java-1.8.0-openjdk rpms. Everything worked fine until some months ago. And with Oracle's JRE 8u192 everything is fine too.

**Comment by dcommander** [comment] 2018-11-30 21:52
OK.  Yeah, if neither of my suggestions help, then it does seem to be something that's out of our control.  You can try the 3.0 pre-release, which embeds Java 11, and if that works, then at least we know that the next major release of TurboVNC will work around this.

**Comment by mlampe** [comment] 2018-11-30 23:30
Your 3.0 pre-release with embedded Java 11 does not show the problem.

But TurboVNC 2.2 + RH's new java-11-openjdk rpm does.

**Comment by dcommander** [comment] 2018-12-01 00:08
Very interesting.  Seems like a Red Hat problem, then.  I'll try again to reproduce.  I didn't update my client system, so it may have still had the older RPM that worked properly.

**Comment by dcommander** [comment] 2018-12-01 00:10
The version of OpenJDK I'm using to build the 3.0 pre-release is the official one from http://jdk.java.net, since that seems to be the best way of eliminating platform-specific idiosyncrasies like this one.  It would still be nice to work around this, though, if possible.

**Comment by dcommander** [comment] 2018-12-04 21:57
I can readily reproduce the problem on CentOS 7 with the latest updates.  Investigating.

**Comment by dcommander** [comment] 2018-12-04 23:02
I looked at the SRPM and unfortunately didn't see anything obvious in the myriad of patches that Red Hat applies to OpenJDK.  For me, doing one of the following works around the problem:

1. Passing `-nocopyrect` to `vncviewer`.  Not sure why that didn't work in your case.
2. Using OpenGL Java 2D blitting by setting (in the environment) `JAVA_TOOL_OPTIONS=-Dsun.java2d.opengl=true`.

I might believe that this is due to some sort of concurrency issue in our CopyRect code, which might have been triggered by Red Hat setting AssumeMP=1 in their implementation of OpenJDK, but (a) I don't know whether AssumeMP=1 actually affects anything if you're running on a multiprocessor system, and (b) that wouldn't explain why `-nocopyrect` had no effect on your system.

Any additional information you can provide is appreciated.

**Comment by dcommander** [comment] 2018-12-04 23:08
Actually, upon further inspection, you don't have to enable OpenGL Java 2D blitting.  Doing that causes the viewer to set `turbovnc.forcealpha=1`, which is what really works around the problem in that case.  So you should be able to set `JAVA_TOOL_OPTIONS=-Dturbovnc.forcealpha=1` in the environment in order to work around it.  That suggests to me that the bug might have been introduced with rh1176206, which pulls libXcomposite into the OpenJDK build, although it is unclear exactly how that is causing the problem.

**Comment by mlampe** [comment] 2018-12-04 23:54
I've tried again and the result is that `-nocopyrect` still doesn't help me, but that both `JAVA_TOOL_OPTIONS=-Dsun.java2d.opengl=true` and `JAVA_TOOL_OPTIONS=-Dturbovnc.forcealpha=1` do.

Nice!

The displaying machine uses the 410.78 driver from nvidia. Otherwise CentOS 7.6 with java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64. And fvwm (no compositing).

**Comment by dcommander** [comment] 2018-12-05 15:47
Thanks for testing!  It would still be nice to work around this issue automatically somehow, but it would take many hours to bisect Red Hat's OpenJDK patches and figure out which one is causing the problem, as well as to diagnose exactly why it is causing the problem.  Ultimately that effort may not produce anything better than the existing `turbovnc.forcealpha` workaround.  For now, I'm closing the issue as SEP, since I can't do anything more with it without assistance or funding.

**Closed by dcommander** 2018-12-05 15:47 UTC
