### ISSUE TITLE
Consider switching to building with zlib-ng

### ISSUE THREAD

**Issue by gdevenyi** [TurboVNC/turbovnc#394] opened 2023-12-20 17:40 UTC
The zlib-ng team have ported and integrated optimizations from a number of different sources, modernized the build and testing system, and squashed various bugs.

https://github.com/zlib-ng/zlib-ng

**Comment by dcommander** [comment] 2023-12-20 18:04
Switching our internal zlib implementation requires a lot of testing, so it isn't a trivial task.  I've already done that once within the past six months (d016d0e1fe028d7bda1c693081caeb9f9cfa85e5, which updated our internal zlib implementation to the latest Intel zlib code), so I'm not in the mood to do so again right now.  However, I will leave this open for consideration in TurboVNC 3.2.  It would be nice to have SIMD acceleration for Arm CPUs, which zlib-ng appears to provide.  However, I would need to thoroughly benchmark it to ensure that it provides significant enough speedup to justify itself on Arm CPUs and that it provides similar speedup to Intel zlib on x86 CPUs.  (That includes SSE2-only CPUs, which TurboVNC still supports.)

**Comment by gdevenyi** [comment] 2023-12-20 18:46
I saw the commit, and I figured I'd highlight the modern project. The other idea of course is to stop directly integrating a versioned copy in the source and take advantage of perhaps submodules and their cmake integration:

https://github.com/zlib-ng/zlib-ng/wiki/Common-build-problems#using-zlib-ng-with-third-party-projects-in-cmake

**Comment by dcommander** [comment] 2023-12-20 19:00
I was already aware of it and have tested it in the past (https://github.com/TurboVNC/turbovnc/issues/95), but that was some years ago.  I'm sure it has improved since then.

**Comment by dcommander** [comment] 2024-08-08 21:21
My latests tests with zlib-ng v2.2.1 in zlib compatibility mode show that it performs amazingly well, but unfortunately it regresses by about 20% in compression ratio when using the Lossless Tight + zlib encoding method.  That makes it a non-starter at the moment.

**Comment by dcommander** [comment] 2024-08-08 21:40
https://github.com/zlib-ng/zlib-ng/issues/1486 shows a similar regression in compression ratio for zlib level 1 (which is what the Lossless Tight + zlib encoding method uses.)

**Comment by gdevenyi** [comment] 2024-08-08 22:28
They've done various tweaks of the speed vs compression ratio for the levels, you probably should test speed and ratio together to make sure you're hitting your target values.

**Comment by dcommander** [comment] 2024-08-08 23:14
I am.  Trust me.  Benchmarking is one of my ninja skills.  I'm using the same [procedures and datasets](https://turbovnc.org/pmwiki/uploads/About/tighttoturbo.pdf) that were used to design the TurboVNC encoder.  I'm comparing, apples to apples, the Lossless Tight + zlib encoding method with the system zlib library, the Intel zlib library (the same code base that the TurboVNC Server currently uses), and zlib-ng v2.2.1.  Lossless Tight + zlib is a mode that is intended for mathematically lossless transmission on bandwidth-constrained networks, so a 20% regression in compression ratio isn't acceptable.  The fact that my results almost exactly matched the results in https://github.com/zlib-ng/zlib-ng/issues/1486 tells me that I probably didn't make a mistake.

**Comment by dcommander** [comment] 2024-08-08 23:16
As near as I can figure, the zlib-ng developers consider this to be expected behavior.  As long as that's the case, there isn't much I can do with it.  It would be nice to have SIMD-accelerated zlib on Arm platforms, but that's not worth a 20% regression in compression ratio on all platforms.  Closing for now.

**Comment by dcommander** [comment] 2024-08-09 15:15
Well, I feel a bit sheepish.  I discovered that disabling the `WITH_NEW_STRATEGIES` CMake variable in the zlib-ng build was the key to eliminating the compression ratio regression.  Disabling that variable disables the "quick" strategy for zlib compression level 1.  Now zlib-ng compresses slightly better than the Intel zlib implementation (0% regression for the 2D datasets and 3% regression for the 3D datasets, relative to zlib v1.2.11, vs. 2% and 5% for Intel zlib.)  It still performs significantly faster than Intel zlib as well (average 46% faster on an SSE2-equipped machine and 121% faster on an AVX2-equipped machine, relative to zlib v1.2.11, vs. 28% and 23% for Intel zlib.)

**Comment by dcommander** [comment] 2024-08-09 15:21
I will do some additional testing with other encoding methods.  Barring any other issues, I will proceed with integrating zlib-ng into the libjpeg-turbo dev branch.  I will also investigate integrating it as a Git submodule with `ExternalProject_add()`.

**Comment by gdevenyi** [comment] 2024-08-09 15:44
Very cool. If the docs are insufficient on the zlib-ng side about WITH_NEW_STRATEGIES perhaps a Issue/PR to improve there would help future users with specific needs like this project does :+1:

**Comment by dcommander** [comment] 2024-08-12 16:19
zlib-ng has been integrated into the dev branch and is fully working in the latest dev/3.2 Evolving pre-release builds.

**Closed** 2024-08-12 16:19 UTC
Labels: enhancement, implemented
