### ISSUE TITLE
Auto resizing in GNOME 2 puts applets in the wrong spot

### ISSUE THREAD

**Issue by loganmc10** [TurboVNC/turbovnc#25] opened 2015-12-22 21:05 UTC
I tested this in 2 cases:
TigerVNC server (nightly) + TurboVNC Java Viewer
TurboVNC server (2.1alpha) + TurboVNC Java Viewer

With the TigerVNC server, if you make the Viewer window full screen, it arranges the GNOME 2 applet icons properly in the panel (for instance the clock on the top right is "snapped" to the right edge). With the TurboVNC server, it "leaves them where they were", making the panel look a little jumbled.

I have attached a screenshot that demonstrates the problem.

![12-22-2015 1-59-13 pm](https://cloud.githubusercontent.com/assets/848146/11965822/8d58d14a-a8b4-11e5-817c-0a42bc6498ce.png)

**Comment by dcommander** [comment] 2015-12-23 00:56
Was this with the latest & greatest TurboVNC Server or with 2.0.1?  The reason I ask is that I have a suspicion that something I fixed as part of d8162802a97cf799ed9e7e868c9b1c4f67a8cdfc (which is currently only available in the 2.1 alpha pre-release) might be the root of this issue as well.  Basically, TurboVNC's X RANDR implementation wasn't notifying certain other parts of the X server when the screen size changed.  It's a one-line fix, and it was necessary to make the extended input device stuff work properly.  I didn't back-port it to 2.0.x because I couldn't find a test case that demonstrated the need for that patch under 2.0.x, but perhaps this is the test case I was looking for.

**Comment by loganmc10** [comment] 2015-12-23 02:29
This was using the Dec 18 alpha build (server and client), server is RHEL 6, client/Java Viewer on Windows 7.

**Comment by dcommander** [comment] 2015-12-23 15:24
Can't reproduce.  On my system, both servers properly rearrange the icons.

**Comment by loganmc10** [comment] 2015-12-23 18:34
Hmm OK I'll look into my system configuration more.

**Comment by dcommander** [comment] 2015-12-23 19:12
Please do not close the issue until resolved.

**Comment by loganmc10** [comment] 2015-12-28 16:12
I reset my GNOME panel settings (rm -rf ~/.gconf/apps/panel). It seems be ok now. I guess between playing around with HP Remote Graphics, and multiple versions of Tiger and Turbo VNC on the same machine something stopped working along the way. A "fresh" copy of the GNOME panel and TurboVNC 2.1 alpha works.

**Closed** 2015-12-28 16:36 UTC
