### ISSUE TITLE
Issues with lock-screen on Ubuntu 20.04 with standard Gnome desktop

### ISSUE THREAD

**Issue by Robo8920** [TurboVNC/turbovnc#253] opened 2020-12-04 11:38 UTC
I am not able to unlock the screen lock in a TurboVNC session on Ubuntu 20.04 when I access the session from Win10.
I can key-in my password but nothing happens when I press "Enter" - no error.. nothing...
Even an unlock via "loginctl" does not always work. I did not have the same issue sofar when I did try to connect from a LINUX client to the session.

**Comment by dcommander** [comment] 2020-12-04 19:41
Duplicate of #238.  This is a known issue with a couple of straightforward workarounds, but I'm not sure of the cause.  It occurs on Fedora 31 as well, but not on Fedora 30 or 32, which suggests an underlying GNOME 3 bug that has since been fixed.  I am continuing to investigate it as I have time.  If you would like to discuss further, please do so under the initial issue report.

**Closed by dcommander** 2020-12-04 19:41 UTC
