### ISSUE TITLE
Single key press produces accent character

### ISSUE THREAD

**Issue by davispuh** [TurboVNC/turbovnc#221] opened 2020-05-23 22:05 UTC
I'm using two Arch Linux computers which both have
```
$ localectl
System Locale: LANG=lv_LV.UTF-8
VC Keymap: lv-tilde
X11 Layout: lv
X11 Model: pc105
X11 Variant: tilde
```

One is TurboVNC server and other is TurboVNC viewer (both using 2.2.4).
In this layout pressing single apostrophe/tilde key  `` ` ``  followed by letter (eg. `a`) produces accent character such as `ā`.
Now the bug is that sometimes in VNC viewer pressing single key (eg. `a`) always produces characters with accents like `ā`, `ē` and so on without pressing apostrophe `` ` ``
At first this behavior was really confusing as it happened only sometimes, but now I've narrowed it down that when in VNC viewer I press `~` (holding shift and pressing apostrophe `` ` ``) it makes it to enter in this state that all key presses will produce accent characters.
Pressing `~` again doesn't change anything but I found that pressing apostrophe twice `` ` ` `` makes it return back to normal. Also pressing apostrophe once or twice works correctly and doesn't cause any weird behavior so it's only `~`

So you can imagine how confusing this was
```
$ ls
$ cd ~
$ lš
bash: lš: command not found
```

**Comment by davispuh** [comment] 2020-05-23 22:13
Also forgot to mention that after pressing `~` none of arrow keys/home/end and such won't work but will produce something like this `[1;1A[1;1B[1;1C[1;1D[1;1F[1;1H`

**Comment by dcommander** [comment] 2020-05-23 22:56
Any chance this is a duplicate of #194?  If so, it's a known bug in Java.

**Comment by davispuh** [comment] 2020-05-24 01:26
I'm not sure, that issue seems to very broad so it's hard to say it might cover this case aswell but for my case everything seems to be working fine like pressing apostrophe `` ` `` (ie. dead key) followed by letter (eg. `u`) does produce `ū` which is expected behavior.
The only thing that causes issue is that by holding shift and pressing apostrophe to write `~` it does write it but it also makes VNC session to enter this state that all next key presses writes accented characters even when they shouldn't.
Without VNC normal behavior for this layout is that `~` isn't counted as dead key so holding shift, pressing apostrophe and pressing letter doesn't produce accented character but always writes `~`.
Also I'm using latest OpenJDK 13.0.2

**Comment by dcommander** [comment] 2020-12-04 23:46
Sorry for the extreme delay in getting around to this.  It's been a hell of a year.  :|  I can confirm that it's a Java bug, similar to the ones described in #194.  I think the best solution to this and other such bugs is for me to finish the implementation of #108, but given the current lack of funding for TurboVNC, I can't make any promises as to the timeframe of that.

**Comment by davispuh** [comment] 2020-12-05 00:26
No worries, it's fine, still thanks! :yum:

**Comment by dcommander** [comment] 2021-12-21 21:53
Closing in favor of #108, which is a partially completed feature that should work around this issue and #194.  The most expedient way to resolve such issues would be for an organization to fund the labor necessary for me to finish #108.

**Closed by dcommander** 2021-12-21 21:53 UTC
Labels: bug
