### ISSUE TITLE
TurboVNC with grabkeyboard=always does not work correctly with Virtual Desktops

### ISSUE THREAD

**Issue by naatje80** [TurboVNC/turbovnc#217] opened 2020-04-21 13:30 UTC
One of our users noticed some strange behaviour when using the turbovnc viewer with Virtual Desktops in Windows 10 (we are using either 1803 or 1809 version of Windows 10; but I could not quickly find when this feature has been added to Windows). Also the "Grab Keyboard" preference should be turned on (we start the client using the option -grapkeyboard always). 

When switching between desktops using the key combination: Ctrl+Windows_Key+Right (or Left) arrow and then switching back to the desktop on which the VNC viewer resides, the VNC Windows somehow seems to let Windows "think" that the Windows key is always pressed. When e.g. pressing D it will now show/hide desktop or when pressing S it will open that startup menu. This is also still the case if the TurboVNC viewer Window has the focus again.

We are only able to unlock this stuck Windows key by clicking on the windows desktop and pressing the Windows key. This seems to fix it, until one switches between de desktop using the key combination mentioned before. 

When only one desktop is created, the same key combination (which does nothing, because only one desktop is available) is also not triggering the stuck Windows key. So it only seems to be happening when multiple desktops are created.

**Comment by dcommander** [comment] 2020-04-22 03:50
Try the 2.2.x stable pre-release build: https://turbovnc.org/DeveloperInfo/PreReleases.  This should already be fixed in that build, which will become 2.2.5 within the next couple of weeks.

**Comment by dcommander** [comment] 2020-04-22 03:50
I will look into the lack of synchronization between the command line options and the GUI.

**Comment by naatje80** [comment] 2020-04-22 06:01
Thank you again for your quick reply. Unfortunately the issue is not resolved in the latest release. It is also a little bit difficult to exactly describe the problem. At first, when the user reported this issue, I also did not correctly understand what this issue was until I experienced it myself. I will try to create a short video of the issue. By the way, I noticed that the current stable build release is compiled with debug mode enable, because it default displays a lot of output in the command line window.

**Comment by naatje80** [comment] 2020-04-22 09:04
@dcommander: I've uploaded a video on youtube to explain the issue: https://youtu.be/XtNr1Vss730. I only captured a port of my screen, but it should be clear what is causing the issue. I hope this is helpful.

**Comment by dcommander** [comment] 2020-04-29 22:52
Regarding the command line/GUI synchronization issue, I think you're probably running into a known limitation of the Windows TurboVNC Viewer:

1. If you pass `-grabkeyboard always` on the command line and also specify a VNC server on the command line, then (assuming the viewer successfully connects to the specified VNC server) keyboard grabbing will be on, and "Always" will be saved as the default keyboard grabbing mode for that connection (meaning that, the next time you connect to the same VNC server, you won't need to specify `-grabkeyboard always`.)

2. If you pass `-grabkeyboard always` on the command line but do not specify a VNC server on the command line, then the "New TurboVNC Connection" dialog pops up.  That dialog loads the previously saved options for the connection specified in the "VNC server:" field, if those options exist.  If those options exist, then they override any options specified on the command line.

In short, in the Windows TurboVNC Viewer, the command-line options take precedence if you specify the VNC server on the command line, but the GUI options take precedence if you specify the VNC server in the GUI.

I think what's happening is that the connection specified in the "New TurboVNC Connection" dialog has saved options associated with it (NOTE: you can clear those saved options by clicking "Clear the list of saved connections" under the "Global" tab in the TurboVNC Viewer Options dialog), and the keyboard grabbing mode in those saved options isn't "Always".  That's why the keyboard grabbing mode doesn't get set to "Always", even though you are specifying that on the command line.  I recognize that this is non-intuitive behavior, but it's behavior that we inherited from TightVNC.  It will be fixed in TurboVNC 3.0, which is using a new unified TurboVNC Viewer code base.

**Comment by dcommander** [comment] 2020-04-29 23:28
As far as the keyboard issue, I was able to reproduce it once, but then the issue went away, and I can no longer reproduce it.  I'm still investigating.

**Comment by dcommander** [comment] 2020-04-29 23:41
If things are working properly, then the Windows key should be passed to the server when keyboard grabbing is on.  Ctrl+Win+Left or Ctrl+Win+Right should not activate another Windows virtual desktop if keyboard grabbing is on.  Thus, I suspect that somehow keyboard grabbing is being temporarily defeated.  I wish I knew why, though.  I've tried every possible combination of those keystrokes but can't get the issue to reproduce again.

**Comment by dcommander** [comment] 2020-04-29 23:46
Never mind.  I can reproduce it again.

**Comment by naatje80** [comment] 2020-04-30 05:37
Thank you for your clarification, in this case we are not struggling with getting the value correctly set. But I assume it is due to some previous cases I've submitted in which we encountered issue with setting up other settings via the command line. It is good to know what the behavior is.

Good to know you are able to reproduce it. We are fully understand you were not able to test every keystroke. In fact, I also did not encountered it before, until one of our users pointed out that he was causing this issue with Windows 10 virtual desktop. In fact, I was not aware this featured was already added to Windows 10 (although did remember I read the I've read something about this feature that would be added to one of the upcoming releases add that time).

**Closed** 2020-05-01 22:03 UTC
Labels: bug

**Comment by dcommander** [comment] 2020-05-01 22:08
Fix pushed and is now available in the 2.2.x stable pre-release build.

**Comment by dcommander** [comment] 2020-05-05 19:53
@naatje80 Please test the fix as soon as you can.

**Comment by naatje80** [comment] 2020-05-06 13:13
@dcommander Thank you again, the issue is indeed resolved! We only noticed the latest stable pre build release of the viewer always opens a debug Window, which is not the case for the normal stable releases.

**Comment by dcommander** [comment] 2020-05-06 18:49
Weird.  Can you post a video of that?

**Comment by dcommander** [comment] 2020-05-06 20:04
I cannot reproduce any issue whereby the debug console opens when using the 2.2.x pre-release build on Windows.  Please supply more details.

**Comment by naatje80** [comment] 2020-05-07 05:33
@dcommander Sorry for the inconvenience. We have written a VNCwrapper application for users to allow them to easily maintain there VNC connections. Together with that, we copy the turbo vncviewer to a location within the profile of the user. We also rename the executable and include the "brand" name and release version, to allow us to quickly test and differentiate the different versions or other VNC viewers. But I just noticed I accidentally renamed and copied the cvncviewer to our environment :(. I'm very sorry for the unnecessary testing from your side!
