### ISSUE TITLE
Popup issue in KDE

### ISSUE THREAD

**Issue by amitkumars1985** [TurboVNC/turbovnc#101] opened 2017-08-20 09:02 UTC
VNC version :- TurboVNC 2.1
OS  : RHEL 7.2
Desktop Manager : KDE
Error :  Popup "Authentication is required to create a color managed device" coming

Is there any way to fix this popup coming every time when users log into their VNC session using KDE as Desktop Manager.

**Comment by dcommander** [comment] 2017-08-20 13:46
Probably a duplicate of https://github.com/TurboVNC/turbovnc/issues/47

**Comment by dcommander** [comment] 2017-08-28 18:47
Closing as duplicate.  Please add a comment if the workaround described in #47 doesn't fix the issue.  I have never personally seen this issue with KDE, but it's a known issue with GNOME 3 on RHEL 7, so I'm assuming it's the same.

In general, I advise users of recent Linux distributions to switch to MATE rather than following GNOME and KDE down their respective rabbit holes.  GNOME and KDE have evolved such that they generally require graphics hardware acceleration in order to perform well.  You can make GNOME 3 work with software OpenGL, but it's sluggish.  KDE Plasma 5 and later won't even work with software OpenGL-- they require hardware OpenGL, so the only way to use those later KDE releases with TurboVNC is to run the window manager with VirtualGL.  With recent GNOME and KDE releases, there are handful of issues such as this that have arisen due to the fact that the designers didn't take into account non-root X servers like TurboVNC (refer to https://github.com/TurboVNC/turbovnc/issues?utf8=%E2%9C%93&q=label%3A%22GNOME%203%22 and https://turbovnc.org/Documentation/Compatibility).

If I can somehow reproduce this issue with KDE, then I'm happy to add a note about it to the aforementioned window manager compatibility report.  Otherwise, the only thing I can suggest is to try the workaround mentioned [here](https://bugzilla.redhat.com/show_bug.cgi?id=1149893), which is known to fix this with GNOME 3, or to switch to MATE.

**Closed by dcommander** 2017-08-28 18:47 UTC
