### ISSUE TITLE
Nvidia driver 440 and above causing slow network speed

### ISSUE THREAD

**Issue by Dyotty** [TurboVNC/turbovnc#249] opened 2020-11-10 01:36 UTC
I'm using virtualgl 2.6.3 and turbovnc 2.2.5 on Ubuntu 16.04, RTX2080Ti PC.
They work only when nvidia driver is driver version 418 or lower.
When using nvidia driver 440 or higher, the network speed becomes extremely low after one minute or so.

**Comment by dcommander** [comment] 2020-11-10 03:52
Likely duplicate of https://github.com/VirtualGL/virtualgl/issues/120.  Please add the `HardDPMS` option to **xorg.conf**, as suggested in that issue.  Also, please do not file VirtualGL issues here.  There is a separate issue tracker for VirtualGL: https://github.com/VirtualGL/virtualgl/issues
TurboVNC itself does not interact with the nVidia driver at all, so any issue that is specific to that driver or any GPU driver is a VirtualGL issue.

**Closed by dcommander** 2020-11-10 03:52 UTC
