### ISSUE TITLE
[Fedora 32][v2.2.5] "Oh no" screen + black screen on VNC viewer

### ISSUE THREAD

**Issue by eliquinox** [TurboVNC/turbovnc#248] opened 2020-10-29 18:44 UTC
When starting the server on Fedora 32, the "Oh no" screen pops out, which logs out the current user if "log out" is pressed. When viewer is connected to the session the screen is black, though the session is successfully established.

I have exhausted a number of possibilities and the only remotely related observation is the result of `journalctl`:

```
gnome-session[6624]: gnome-session-check-accelerated: no X11 display found
gnome-session[6629]: gnome-session-check-accelerated: no X11 display found
gnome-session[6564]: gnome-session-binary[6564]: WARNING: software acceleration check failed: Child process exited with code 1
gnome-session-binary[6564]: WARNING: software acceleration check failed: Child process exited with code 1
gnome-shell[2505]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
```

Do let me know what further info you need to probe this problem further.

**Comment by dcommander** [comment] 2020-10-29 21:17
After the window manager fails to start, the TurboVNC X server should still be active. From an SSH shell, try running `glxinfo` and redirecting it to the TurboVNC X server (e.g. `DISPLAY=:1 glxinfo`. That will tell me whether there is an issue with Mesa.

**Comment by eliquinox** [comment] 2020-10-30 09:08
Here is the entire output of the command: https://gist.github.com/eliquinox/0d5fe1fc706eb8f03132b7b063557150
Let me know if you need anything else to diagnose the issue.

**Comment by eliquinox** [comment] 2020-10-31 15:03
After deleting `/etc/systemd/system/vncserver@.service` that I have created as a result of following https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/infrastructure-services/TigerVNC/
before switching to TurboVNC, I am able to establish a VNC session without the black screen issue mentioned above. I am marking this as resolved but am curious as to why that service file interfered with a TurboVNC session, so any pointers will be appreciated.

**Comment by dcommander** [comment] 2020-10-31 15:57
I'm curious about that as well. I'll try to reproduce the issue in my Fedora 32 VM.

**Comment by dcommander** [comment] 2020-12-01 16:33
I wasn't able to repro the issue, unfortunately.  I did:

```
# dnf install tigervnc-server
# cp /lib/systemd/system/vncserver@.service /etc/systemd/system/vncserver@.service
# systemctl daemon-reload
```
and edited **/etc/tigervnc/vncserver.users**, as instructed.  Then I deleted **~/.vnc/xstartup.turbovnc**, installed TurboVNC 2.2.5, and started it with `/opt/TurboVNC/bin/vncserver`.  GNOME 3 started in the TurboVNC session, as expected.  However, I wasn't able to successfully start the TigerVNC Server before trying the TurboVNC Server, so perhaps that's a critical piece of the puzzle.

**Comment by dcommander** [comment] 2020-12-01 16:52
I was finally able to get the TigerVNC Server to start.  I still can't reproduce the issue.  For me, the TurboVNC Server even works properly while the TigerVNC Server is running on a different display.

**Comment by dcommander** [comment] 2020-12-01 16:53
Feel free to post additional comments if you have further information that may help me repro the issue, but I'm closing as WFM for now.

**Closed by dcommander** 2020-12-01 16:52 UTC
