### ISSUE TITLE
vncserver can not start when install from source: Font Path

### ISSUE THREAD

**Issue by liuty10** [TurboVNC/turbovnc#136] opened 2018-08-14 21:39 UTC
Hi, I am trying to install TurboVNC from source code and I followed the build step in BUILDING.MD. But when I try to start the vncserver, I encounter the following error. Can you give me some advice on what I should do next?

WARNING: The first attempt to start Xvnc failed, possibly because the vncserver
script was not able to figure out an appropriate X11 font path for this system
or because the font path you specified with the -fp argument was not valid.
Attempting to restart Xvnc using the X Font Server (xfs) ...
Could not start Xvnc.

Unrecognized option: -x509cert
use: X [:] [option]
-a # default pointer acceleration (factor)
-ac disable access control restrictions
-audit int set audit trail level
.......

Addition, when I download the deb package and install use "dpkg -i xxx.deb", the vncserver works well.

**Comment by dcommander** [comment] 2018-08-14 22:07
Which version of TurboVNC are you building, and how are you building it?

That warning is generated by vncserver any time Xvnc fails to start.  The vncserver script has no idea why Xvnc failed to start.  That's why it says that the failure was **_possibly_** related to the font path, which is historically the most common reason why Xvnc won't start.  However, in your case, this error is obviously the cause:

"Unrecognized option: -x509cert"

That error should have been fixed long ago (in 2.1), which is why I ask which version of the code you are building.

**Comment by liuty10** [comment] 2018-08-14 22:18
Hi, 
Thank you very much for your reply.

1. which version?
It is turbovnc_2.1.91_amd64.deb. I compiled the source code from github and make a deb package.

2. How I build?
    sudo apt install cmake
    sudo apt install libx11-dev
    sudo dpkg -i libjpeg-turbo-official_2.0.0_amd64.deb
    sudo apt-get install libpam0g-dev
    git clone https://github.com/TurboVNC/turbovnc.git
    mv turbovnc turbovnc-git
    mkdir turbovnc-git-package
    cd turbovnc-git-package
    cmake -G"Unix Makefiles" ../turbovnc-git
    make
    sudo make install

**Comment by liuty10** [comment] 2018-08-14 23:07
I would like to add more information.

lty@AI:/opt$ ./TurboVNC/bin/vncserver -list
TurboVNC server sessions:
X DISPLAY #	PROCESS ID

lty@AI:/opt$ ./TurboVNC/bin/vncserver
WARNING: The first attempt to start Xvnc failed, possibly because the vncserver
script was not able to figure out an appropriate X11 font path for this system
or because the font path you specified with the -fp argument was not valid.
Attempting to restart Xvnc using the X Font Server (xfs) ...
Could not start Xvnc.
Unrecognized option: -x509cert
use: X [:<display>] [option]
-a #                   default pointer acceleration (factor)
-ac                    disable access control restrictions
-audit int             set audit trail level
-auth file             select authorization file
-br                    create root window with black background
+bs                    enable any backing store support
.........

lty@AI:/opt$ ./TurboVNC/bin/vncserver -list
TurboVNC server sessions:
X DISPLAY #	PROCESS ID
:1		32067
(It is very weird here. It seems that Xvnc was launched)

lty@AI:/opt$ ./TurboVNC/bin/vncviewer localhost:5901
libjawt.so path: /usr/lib/jvm/java-8-oracle/lib/amd64
Could not connect: Connection refused

lty@AI:/opt$ ./TurboVNC/bin/vncserver -kill :1
Killing Xvnc process ID 32067
Xvnc process ID 32067 already killed

**Comment by liuty10** [comment] 2018-08-15 18:54
I tried to replace my compiled 'Xvnc' with your released 'Xvnc', and it works well. So, there must be something wrong with the building method(or the depending packages) or source code.

**Comment by dcommander** [comment] 2018-08-15 19:09
Please be patient.  I have not yet had time to attempt to reproduce the problem.

**Comment by liuty10** [comment] 2018-08-16 14:43
Hi 
I think I solved the problem. But I am not 100% sure.
The program stops in following function:

void ProcessCommandLine(int argc, char *argv[])

This function is called in /unix/Xvnc/programs/Xserver/dix/main.c 
and implemented in /unix/Xvnc/programs/Xserver/os/utils.c

There are two command flags "-x509cert" and "-x509key" that are not deal with in ProcessCommandLine function in utils.c

My solution: 
Comment the two command option in vncserver which is a perl script, like this:

# Now start the X VNC Server
$cmd = $exedir."Xvnc :$displayNumber";
$cmd .= " -dpi $dpi" if ($dpi);
$cmd .= " -desktop " . &quotedString($desktopName);
$cmd .= " -httpd $vncClasses" if ($enableHTTP && $vncClasses);
$cmd .= " -auth $xauthorityFile";
$cmd .= " -geometry $geometry" if ($geometry);
$cmd .= " -depth $depth" if ($depth);
$cmd .= " -pixelformat $pixelformat" if ($pixelformat);
$cmd .= " -rfbwait 120000";
$cmd .= " -rfbauth $passwdFile" if ($authTypeVNC);
#$cmd .= " -x509cert $x509CertFile" if ($encTypeX509);
#$cmd .= " -x509key $x509KeyFile" if ($encTypeX509);
$cmd .= " -securitytypes $securityTypes" if ($securityTypes);
$cmd .= " -rfbport $vncPort";
$cmd .= " -fp $fontPath" if ($fontPath);
$cmd .= " -alr ".$autoLosslessRefresh if ($autoLosslessRefresh > 0.0);
$cmd .= " -deferupdate $deferUpdate";
$cmd .= " -xkbdir $xkbdir" if ($xkbdir);
$cmd .= " -xkbcompdir $xkbcompdir" if ($xkbcompdir);
$cmd .= " -pamsession" if ($pamSession);
$cmd .= " -dridir $dridir" if ($dridir);
$cmd .= " -registrydir $registrydir" if ($registrydir);
$cmd .= " -nomt" if (!$multiThread);
$cmd .= " -nthreads $numThreads" if ($numThreads);

How do you think about the above solution? Is it right?
---------------------------------------------------------------------------
I am trying to get the round time delay for gamers' behaviour and the time eclipsed on Server side and network respectively . Is there any easier way to get this performance metrics? Or I have to synchronize the machine time and insert some hooks by hand? Thank you very much.

**Comment by dcommander** [comment] 2018-08-16 16:45
Please stand by and let me look at this on my own.  As I said, this issue was supposed to be fixed, so I need to verify whether this represents a regression.

**Comment by dcommander** [comment] 2018-08-16 23:04
Fixed in master

**Comment by liuty10** [comment] 2018-08-16 23:04
Thanks!

**Closed** 2018-08-16 23:04 UTC
