### ISSUE TITLE
Ctrl-... – what happens? (Ctrl seems to "stick")

### ISSUE THREAD

**Issue by ZPMU** [TurboVNC/turbovnc#216] opened 2020-04-09 07:58 UTC
Hello there,

I'm using TurboVNC on a Linux Mint machine and connecting to a UltraVNC server on a Windows 10 machine. On that machine there I got a Git Bash window. When trying to type a command on that Bash window, I want to type Ctrl-R to do Bash’s reverse-i-search. The Bash responds as usual – i.e. it receives Ctrl-R. But from then on, it seems as in my complete VNC session there is something like a Ctrl-key-lock active. I have to fiddle around with TurboVnc’s "Ctrl"-button to release the Ctrl-lock.

I think, maybe a problem is my limited knowledge about TurboVNC’s keyboard shortcuts.

How to release Ctrl-lock by keyboard? What can I do to send Ctrl-R without described side effect?
I cruised through the manual, but it seems to give little infos about Ctrl-key combinations.

Thanks for any hints – Peter

TurboVNC v2.2.4
UltraVNC Server 1.2.4.0
I installed UltraVNC according to https://turbovnc.org/Documentation/UltraVNC

**Comment by dcommander** [comment] 2020-04-09 15:24
I can't reproduce the issue.

**Comment by dcommander** [comment] 2020-04-09 15:28
I can confirm, however, that Ctrl-R has no special meaning in TurboVNC.  The viewer should just send that keystroke to the server.  If you launch the viewer with `-loglevel 100`, you can see it sending keystrokes, which will allow you to verify that Ctrl is released:

```
CConn: key PRESS, code Ctrl (17), loc LEFT, char 65535 => 0xffe3
CConn: key PRESS, code R (82), loc STANDARD, char 18 LCtrl => 0x0072
CConn: key release, code R (82), loc STANDARD, char 18 LCtrl => 0x0072
CConn: key release, code Ctrl (17), loc LEFT, char 65535 LCtrl => 0xffe3
```

**Comment by ZPMU** [comment] 2020-04-12 00:37
So, probably you suggest it is a problem on Win-side and UltraVNC?

When I launch viewer with `-loglevel 100`, I see no output when clicking "Send ctrl press/release" button – albeit clicking it twice will remedy ctrl lock for the time being.

Thanks anyway – Peter

**Comment by dcommander** [comment] 2020-04-12 01:17
I’ll check, but it’s possible that the toolbar buttons bypass the log.

**Comment by dcommander** [comment] 2020-04-12 01:18
I have no idea whether it is an issue with UltraVNC or not. I need to be able to reproduce the problem before I can conclude anything about it.

**Comment by dcommander** [comment] 2020-04-12 01:19
Also, I meant that you should use the log to verify that the Ctrl-R sequence is being sent correctly.

**Comment by ZPMU** [comment] 2020-04-12 18:42
Sorry, forgot to mention: The toolbar button gives no output (as already mentioned), but Ctrl-R output looks like dcommander described (except that instead of "Ctrl" there is "Strg" printed – I think a locale issue due to my german keyboard layout).

**Comment by ZPMU** [comment] 2020-04-16 08:40
Some supplements:
Other Ctrl key combinations (Ctrl-C and/or Ctrl-V, Ctrl-Tab) are an issue, too. Ctrl-R was just the first I encountered.
When using another VNC client (Remmina), this issue doesn't persist, so I suppose (maybe from a naïve point of view?) it's a TurboVNC-client issue and not a UltraVNC-server issue.
After all, if the issue could not be confirmed and I am happy working with Remmina, the issue may be closed.
I leave it open now. Maybe I can answer someone's questions or do some testing.

**Comment by dcommander** [comment] 2020-05-01 22:38
I still can't reproduce the issue, even with a German keyboard layout on the client and the same version of UltraVNC that you are using on the server.  I have verified, using the TurboVNC Server and `xev`, that the Ctrl-{letter} key sequences are properly transmitted and received.  The only major difference in my environment is that I'm using Ubuntu 18.04 on the client rather than Linux Mint.  I am closing the issue, but if you have any further information, you can still add comments.

**Closed by dcommander** 2020-05-01 22:38 UTC
