### ISSUE TITLE
Copy Paste Issue

### ISSUE THREAD

**Issue by amitkumars1985** [TurboVNC/turbovnc#105] opened 2017-08-28 13:17 UTC
VNC : TurboVNC 2.1.1 x86
Server OS : RHEL 6.7
Client OS : Windows 10
Java Version : JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
Java VM: Java HotSpot(TM) Client VM (25.91-b14 mixed mode windows-x86 )

In specific scenario copy paste from windows host to linux VNC session doesn't work. 

The key is to keep both notepad in Windows and TurboVnC window side by side. 
Select text in linux and hit middle mouse button there .
Then go to notepad window, select text and copy.
Then click with middle mouse button in Turbovnc window => linux text is pasted. After second middle button press text from Win is pasted (linux text highlight goes away in the first middle button press. )

It seems clipboard buffer of VNC is not overwritten by text copied on windows machine, so it still assumes selected text in linux as content to copy and when selection goes away, it copies the windows text. 

Any suggestion on how this can be managed ?

**Comment by dcommander** [comment] 2017-08-28 14:00
I think this is a duplicate of #20, but you provided some critical details that I was missing.  Hopefully I'll be able to reproduce it now.  Stand by.

**Comment by dcommander** [comment] 2017-08-29 01:37
Unfortunately, I don't think this is the same issue as #20, but it is a legit issue all the same.  Our Windows native viewer behaves as expected and de-selects the text on the server if the clipboard changes on the client.  I'll look into how to make the Java viewer do likewise.

**Comment by dcommander** [comment] 2017-09-09 02:37
Fix pushed.

**Closed** 2017-09-09 02:36 UTC
