### ISSUE TITLE
TurboVNC on Windows 10: Black Screen/Rendering Issues

### ISSUE THREAD

**Issue by j4th** [TurboVNC/turbovnc#168] opened 2019-03-19 19:23 UTC
Running TurboVNC on a brand-new laptop and running into issues I haven't had before, so I apologize for not being more experienced with working with the software.

I am running TurboVNC 2.2.1 64-bit release on Windows 10 build 18356.1; display resolution is 3840x2160 but I have tried it at 1920x1080 as well which I know works fine on my desktop. Graphics card is an integrated Intel UHD 620.

I have no problem connecting to the server as I usually would, but upon connection I am given a black screen that at times flashes with the display, but it is clearly scaled wrong. I am unable to execute keyboard shortcus (eg. fullscreen). I am using this for a grad course so I do not have control over the host, but I have someone that can work with me to resolve the problem if possible.

Do I need to configure VirtualGL, is that where my issues is? I am finding it odd I am the only person in the lecture having this issue, and it is only on my new laptop to boot. Any help is GREATLY appreciated!

**Comment by dcommander** [comment] 2019-03-19 20:01
So, just to be 100% clear, nothing changed on the server, it was working fine before, and the only thing that changed was your client machine?  Also, have you reproduced this problem with both the native TurboVNC Viewer and the Java TurboVNC Viewer?  (Both are installed when you install our official TurboVNC package for Windows.)

If both the native and Java viewers fail in the same way, then I would strongly suspect that something did change on the server.  It only one viewer fails, then it may be a legitimate viewer bug, although I've never seen it before.

**Comment by dcommander** [comment] 2019-03-19 20:36
And no, it doesn't have anything to do with VirtualGL.

**Comment by dcommander** [comment] 2019-03-26 21:18
Can you answer my questions above?  Thanks.

**Comment by j4th** [comment] 2019-03-26 21:35
Hey sorry, I've had extensive back-and-forth with the server admin trying to resolve this as it most definitely  not unique to my TurboVNC install; I can repliate the issue on the admin's computer he usually uses to connect.

RE the clarifications: yes it was an issue that occurred after I had already been using the server for at least a month. The Java I have not been able to get to work, I get a cert error and the admin said he hasn't gotten it configured/to work for himself or something along those lines.

This is the error I get in my home/.vnc/ log for the display when I start one:

```
25/03/2019 18:47:59 VNC extension running!
Invalid MIT-MAGIC-COOKIE-1 keyxrdb: Resource temporarily unavailable
xrdb: Can't open display ':3'
Invalid MIT-MAGIC-COOKIE-1 keyxmodmap:  unable to open display ':3'
Invalid MIT-MAGIC-COOKIE-1 keyInvalid MIT-MAGIC-COOKIE-1 key/usr/bin/xmbind:  Can't open display
Invalid MIT-MAGIC-COOKIE-1 key
** (gnome-session:32219): WARNING **: Cannot open display:
```

At this point any advice is appreciated; I found [this](https://iwf1.com/quick-fix-invalid-mit-magic-cookie-1-sudo) and forwarded it to the admin but do not know if he has looked at the two solutions in there beyond deleting .Xauthority. I have tried killing my display, deleting the xstartup and Xauthority files, and restarting the display; I always get the above errors.

Any advice is GREATLY appreciated at this point, as I will in the mean time have to work without a GUI for the class. I will do better at responding!

**Comment by dcommander** [comment] 2019-03-26 22:11
If you don't mind, please test the latest 2.2.x stable pre-release build from https://turbovnc.org/DeveloperInfo/PreReleases and see if that eliminates the cert error in the Java viewer.  I think it should, but otherwise, please provide more details about the failure.  TurboVNC 3.0 is moving to the Windows/Java TurboVNC Viewer with an embedded JRE (so no need to install a separate JRE on the client) and eliminating the Windows native TurboVNC Viewer, so I definitely want to fix that issue if it hasn't already been fixed.

A couple of things to try:
- Try connecting to the TurboVNC session using another  VNC viewer, such as the RealVNC or TigerVNC Viewer (or the Windows/Java TurboVNC Viewer, if the 2.2.x pre-release build works.)  Do you still see a black screen?
- From an SSH session on the server, try running a simple application in the TurboVNC session, e.g. `DISPLAY=:1 xterm`.  Connect to the TurboVNC session using the TurboVNC Viewer.  Can you see the xterm window?

If the answer to both questions is "yes", then the problem is that the TurboVNC Server isn't properly starting the window manager.  Make sure you are using the latest official release of the TurboVNC Server, and `rm ~/.vnc/xstartup.turbovnc` so that the server can re-create that file the next time it starts (NOTE: that will no longer be necessary in TurboVNC 3.0, since it is now using a central xstartup.turbovnc file.)  If that doesn't fix the problem, then please provide details regarding your server environment-- specifically, the Linux distribution and version you are using, the TurboVNC Server version you are using, and the window manager you are trying to use.

**Comment by j4th** [comment] 2019-03-26 22:14
I will try all 3 of those things and get back to you! I have tried it on another machine with UltraVNC.

The truly odd thing is that it started suddenly for me, and none of the other 20 or so students have the issue. I'll report back.

**Comment by dcommander** [comment] 2019-03-26 22:16
~/.vnc/xstartup.turbovnc is user-specific, so that might explain why no one else is experiencing it.  The issue might have been triggered by a server upgrade of some kind.

**Comment by j4th** [comment] 2019-03-26 23:00
Same issue through 2.2.2 both Windows and Java viewer.

Don't have the xterm command so I ran a program called tec360 that I know worked for me on the server, got the following:

`Invalid MIT-MAGIC-COOKIE-1 keytec360-bin: cannot connect to X server :3`

I'll ask the admin for the info you requested.

**Comment by dcommander** [comment] 2019-03-26 23:01
But it sounds like 2.2.2 at least eliminated the cert error?

**Comment by j4th** [comment] 2019-03-26 23:03
Yes!
Now it properly connects through Java and I can see the session in the log.

**Comment by dcommander** [comment] 2019-03-26 23:13
OK, great.  Hashtag progress.

**Comment by dcommander** [comment] 2019-03-26 23:19
Oh, and that tec360 error does strongly suggest that there is some issue with your ~/.Xauthority file on the server, which would also explain why the WM isn't starting, but given that you've already tried deleting ~/.Xauthority, I'm also not sure what else to try in that regard.  Sorry I didn't look closely enough at your earlier comment, but it also suggests (based on the TurboVNC session log) that ~/.Xauthority is somehow to blame.  Try deleting that file, restarting the TurboVNC session, then look at the ~/.Xauthority file and make sure it has proper ownership and permissions for your user account.

**Comment by j4th** [comment] 2019-03-26 23:31
Right now the .Xauthority file is mostly nonsense characters with RMIT-MAGIC-COOKIE-1 and server.dept.university.com thrown in. Is that unusual, or is it salted and hashed or something along those lines?

**Comment by dcommander** [comment] 2019-03-27 00:17
I think it's a binary file, so that's not surprising.  I'm mainly interested in the file permissions.  Delete the file, restart TurboVNC, and run `ls -l ~/.Xauthority`.

**Comment by j4th** [comment] 2019-03-27 02:00
Haha sorry, long days for me, but clearly for you too.

`-rw-------. 1 UniversityID users 184 Mar 26 19:58 .Xauthority`

**Comment by dcommander** [comment] 2019-03-27 02:21
OK, but you answered my question without answering my question. Is that your real user name? Seems unlikely that your user name would be “UniversityID.”

**Comment by j4th** [comment] 2019-03-27 02:30
Ah okay sorry, stumbling my way through all of this. I put UniversityID as a placeholder in this and the path earlier, sorry for the extreme lack of clarity. It is the proper name which matches my login to the server through PuTTy.

**Comment by dcommander** [comment] 2019-03-27 02:49
OK, I thought that might be the case but wanted to be sure. (NOTE: surrounding it with braces {} will make it clear that it’s a place holder, for future reference.) So I’m back to not having a clue what’s wrong. Can you do the following?

‘‘‘
/opt/TurboVNC/bin/vncserver -h
cat /etc/os-release
cat /etc/lsb-release
cat /etc/redhat-release
```

**Comment by j4th** [comment] 2019-03-27 22:37
Hey I hope I did this right (curly braces included?); file names were slightly different.
```
TurboVNC Server v2.2.1 (build 20190102)
Scientific Linux release 6.10 (Carbon)
LSB_VERSION=base-4.0-amd64:base-4.0-ia32:base-4.0-noarch:core-4.0-{...}
```
The /etc/system-release file just linked to the /etc/redhat-release file

**Comment by j4th** [comment] 2019-03-27 22:56
Update: Was able to get the server restarted finally and it seems to have done the trick! I am checking if anything was run under my account since I was last on it, but on first glance there's a `.pid` and `.log` file for a display that I didn't have under my `-list` before or after restart.

**Comment by dcommander** [comment] 2019-03-28 00:23
OK, good.  I was just checking the Linux release to see if it was one that is known to work with TurboVNC, and it definitely is:  https://turbovnc.org/Documentation/Compatibility22

**Closed by dcommander** 2019-03-28 00:23 UTC
